branches:
  - main
plugins:
  - '@semantic-release/commit-analyzer'
  - [
      '@semantic-release/release-notes-generator',
      {
        preset: 'conventionalcommits',
        presetConfig:
          {
            types:
              [
                { type: 'feat', section: 'Features' },
                { type: 'impr', section: 'Improvements' },
                { type: 'refactor', section: 'Improvements' },
                { type: 'perf', section: 'Improvements' },
                { type: 'fix', section: 'Bug Fixes' },
                { type: 'ci', section: 'CI' },
                { type: 'docs', section: 'Documentation' },
                { type: 'chore', section: 'Miscellaneous' },
                { type: 'style', section: 'Miscellaneous' },
                { type: 'test', section: 'Miscellaneous' },
                { type: 'build', section: 'Miscellaneous' },
              ],
          },
      },
    ]
  - ['@semantic-release/changelog', { 'changelogFile': 'CHANGELOG.md' }]
  - [
      '@semantic-release/exec',
      {
        'prepareCmd': './scripts/bump-version.sh ${nextRelease.version} && task build',
      },
    ]
  - '@semantic-release/github'
  - [
      '@semantic-release/git',
      {
        'assets':
          [
            'CHANGELOG.md',
            'README.md',
            'Cargo.lock',
            'cli/Cargo.toml',
            'cli/src/cli.rs',
            'cli/templates/.devcontainer/deps.sh.jinja',
            'cli/templates/readme.md.jinja',
          ],
      },
    ]
repositoryUrl: 'https://github.com/edenreich/kopgen'
