
[workspace]
resolver = "2"
members = [
    "crates/client-sdk",
    "crates/k8s-codegen",
    "crates/k8s-crdgen",
    "crates/k8s-operator",
    "tests",
]

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 0
debug = true
codegen-units = 16
