openapi: 3.1.0
info:
  title: Pets API
  version: 1.0.0
paths:
  /cats:
    get:
      summary: Get all cats
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cat'
    post:
      summary: Create a new cat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cat'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cat'
  /cats/{id}:
    get:
      summary: Get a cat by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cat'
        '404':
          description: Not found
    put:
      summary: Update a cat by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cat'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cat'
        '404':
          description: Not found
    delete:
      summary: Delete a cat by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content
  /dogs:
    get:
      summary: Get all dogs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dog'
    post:
      summary: Create a new dog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dog'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dog'
  /dogs/{id}:
    get:
      summary: Get a dog by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dog'
        '404':
          description: Not found
    put:
      summary: Update a dog by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dog'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dog'
        '404':
          description: Not found
    delete:
      summary: Delete a dog by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content
components:
  schemas:
    Cat:
      type: object
      required:
        - name
        - breed
        - age
      properties:
        id:
          type: string
          example: '1'
        name:
          type: string
          example: 'Fluffy'
        breed:
          type: string
          example: 'Persian'
        age:
          type: integer
          example: 3
    Dog:
      type: object
      required:
        - name
        - breed
        - age
      properties:
        id:
          type: string
          example: '1'
        name:
          type: string
          example: 'Fido'
        breed:
          type: string
          example: 'Bulldog'
        age:
          type: integer
          example: 3
