openapi: 3.1.0
info:
  title: Pets API
  version: 1.0.0
paths:
  /cats:
    get:
      tags:
        - cats
      operationId: getCats
      summary: Get all cats
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cat'
              examples:
                Cat:
                  $ref: '#/components/examples/Cat'
    post:
      tags:
        - cats
      operationId: createCat
      summary: Create a new cat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cat'
            examples:
              Cat:
                $ref: '#/components/examples/Cat'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cat'
              examples:
                Cat:
                  $ref: '#/components/examples/Cat'
  /cats/{id}:
    get:
      tags:
        - cats
      operationId: getCatById
      summary: Get a cat by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cat'
              examples:
                Cat:
                  $ref: '#/components/examples/Cat'
        '404':
          description: Not found
    put:
      tags:
        - cats
      operationId: updateCatById
      summary: Update a cat by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cat'
            examples:
              Cat:
                $ref: '#/components/examples/Cat'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cat'
              examples:
                Cat:
                  $ref: '#/components/examples/Cat'
        '404':
          description: Not found
    delete:
      tags:
        - cats
      operationId: deleteCatById
      summary: Delete a cat by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content
  /dogs:
    get:
      tags:
        - dogs
      operationId: getDogs
      summary: Get all dogs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dog'
              examples:
                Dog:
                  $ref: '#/components/examples/Dog'
    post:
      tags:
        - dogs
      operationId: createDog
      summary: Create a new dog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dog'
            examples:
              Dog:
                $ref: '#/components/examples/Dog'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dog'
              examples:
                Dog:
                  $ref: '#/components/examples/Dog'
  /dogs/{id}:
    get:
      tags:
        - dogs
      operationId: getDogById
      summary: Get a dog by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dog'
              examples:
                Dog:
                  $ref: '#/components/examples/Dog'
        '404':
          description: Not found
    put:
      tags:
        - dogs
      operationId: updateDogById
      summary: Update a dog by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dog'
            examples:
              Dog:
                $ref: '#/components/examples/Dog'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dog'
              examples:
                Dog:
                  $ref: '#/components/examples/Dog'
        '404':
          description: Not found
    delete:
      tags:
        - dogs
      operationId: deleteDogById
      summary: Delete a dog by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content
  /horses:
    get:
      tags:
        - horses
      operationId: getHorses
      summary: Get all horses
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Horse'
              examples:
                Horse:
                  $ref: '#/components/examples/Horse'
    post:
      tags:
        - horses
      operationId: createHorse
      summary: Create a new horse
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Horse'
            examples:
              Horse:
                $ref: '#/components/examples/Horse'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Horse'
              examples:
                Horse:
                  $ref: '#/components/examples/Horse'
  /horses/{id}:
    get:
      tags:
        - horses
      operationId: getHorseById
      summary: Get a horse by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Horse'
              examples:
                Horse:
                  $ref: '#/components/examples/Horse'
        '404':
          description: Not found
    put:
      tags:
        - horses
      operationId: updateHorseById
      summary: Update a horse by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Horse'
            examples:
              Horse:
                $ref: '#/components/examples/Horse'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Horse'
              examples:
                Horse:
                  $ref: '#/components/examples/Horse'
        '404':
          description: Not found
    delete:
      tags:
        - horses
      operationId: deleteHorseById
      summary: Delete a horse by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content
components:
  examples:
    Cat:
      value:
        uuid: '76523f74-484c-4018-b9bf-1c03b134512a'
        name: 'Fluffy'
        breed: 'Persian'
        age: 3
    Dog:
      value:
        uuid: '4e817fcd-6c9f-4a15-9bc2-eddac59a10d1'
        name: 'Fido'
        breed: 'Bulldog'
        age: 3
    Horse:
      value:
        uuid: '4e817fcd-6c9f-4a15-9bc2-eddac59a10d1'
        name: 'Star'
        breed: 'Arabian'
        age: 5
  schemas:
    Cat:
      type: object
      required:
        - name
        - breed
        - age
      properties:
        uuid:
          type: string
        name:
          type: string
        breed:
          type: string
        age:
          type: integer
    Dog:
      type: object
      required:
        - name
        - breed
        - age
      properties:
        uuid:
          type: string
        name:
          type: string
        breed:
          type: string
        age:
          type: integer
    Horse:
      type: object
      required:
        - name
        - breed
        - age
      properties:
        uuid:
          type: string
        name:
          type: string
        breed:
          type: string
        age:
          type: integer
