version: '3'

dotenv: ['.env']

tasks:
  docs:
    desc: Open the documentation
    cmds:
      - mdbook serve --open docs --hostname 0.0.0.0

  lint:
    desc: Lint the code
    cmds:
      - cargo fmt --all -- --check

  analyse:
    desc: Analyse the code
    cmds:
      - cargo clippy --all-targets --all-features -- -D warnings

  setup-target:
    desc: 'Conditionally add a Rust target based on TARGET_ARCH'
    cmds:
      - |
        if [ -n "${TARGET_ARCH}" ]; then
          echo "Adding target architecture: ${TARGET_ARCH}";
          rustup target add ${TARGET_ARCH};
        else
          echo "TARGET_ARCH is not set. Skipping target addition.";
          echo "Using default target $(rustup show active-toolchain).";
        fi
    silent: true

  build:
    desc: Build kopgen CLI
    deps:
      - setup-target
    cmds:
      - cargo build {{if eq .RELEASE "true"}}--release {{end}}{{if .TARGET_ARCH}}--target {{.TARGET_ARCH}}{{end}}

  install:
    desc: Install the CLI
    deps:
      - build
    cmds:
      - cargo install --path ./cli --force

  run:
    desc: Run the CLI
    deps:
      - setup-target
    cmds:
      - cargo run {{if .TARGET_ARCH}}--target {{.TARGET_ARCH}} {{end}}--package kopgen -- {{.CLI_ARGS}}

  test:
    desc: Test the project
    cmds:
      - cargo test --all-features

  test-cli-output:
    desc: Test the CLI output
    cmds:
      - cargo run --package kopgen init temp

  pre-release:
    desc: Pre-release the project
    cmds:
      - semantic-release --tag-format 'v${version}-rc' --prerelease rc {{.CLI_ARGS}}
    env:
      CI: true
      TARGET_ARCH: aarch64-unknown-linux-musl

  release:
    desc: Release the project
    cmds:
      - semantic-release {{.CLI_ARGS}}
    env:
      CI: true
      TARGET_ARCH: aarch64-unknown-linux-musl

  clean:
    desc: Clean the project
    cmds:
      - rm -rf temp
      - cargo clean
