version: '3'

dotenv: ['.env']

tasks:
  docs:
    desc: Open the documentation
    cmds:
      - mdbook serve --open docs/operator

  analyse:
    desc: Analyse the code
    cmds:
      - cargo clippy --all-targets --all-features -- -D warnings

  build:
    desc: Build kopegen CLI
    cmds:
      - rustup target add {{.TARGET_ARCH}}
      - cargo build --verbose {{if eq .RELEASE "true"}}--release {{end}}{{if .TARGET_ARCH}}--target {{.TARGET_ARCH}}{{end}}
    requires:
      vars:
        - TARGET_ARCH

  run:
    desc: Run the CLI
    cmds:
      - cargo run --package kopgen -- {{.CLI_ARGS}}

  test-cli-output:
    desc: Test the CLI output
    cmds:
      - cargo run --package kopgen init temp

  clean:
    desc: Clean the project
    cmds:
      - rm -rf temp
      - cargo clean
