version: '3'

dotenv: ['.env']

tasks:
  docs:
    desc: Open the documentation
    cmds:
      - mdbook serve --open docs

  analyse:
    desc: Analyse the code
    cmds:
      - cargo clippy --all-targets --all-features -- -D warnings

  build:
    desc: Build kopegen CLI
    cmds:
      - rustup target add {{.TARGET_ARCH}}
      - cargo build --verbose {{if eq .RELEASE "true"}}--release {{end}}{{if .TARGET_ARCH}}--target {{.TARGET_ARCH}}{{end}}
    requires:
      vars:
        - TARGET_ARCH

  run:
    desc: Run the CLI
    cmds:
      - cargo run --package kopgen -- {{.CLI_ARGS}}

  test:
    desc: Test the project
    cmds:
      - cargo test --all-features --verbose

  test-cli-output:
    desc: Test the CLI output
    cmds:
      - cargo run --package kopgen init temp

  pre-release:
    desc: Pre-release the project
    cmds:
      - semantic-release --tag-format 'v${version}-rc' --prerelease rc
    env:
      CI: true
      TARGET_ARCH: aarch64-unknown-linux-musl

  release:
    desc: Release the project
    cmds:
      - semantic-release
    env:
      CI: true
      TARGET_ARCH: aarch64-unknown-linux-musl

  clean:
    desc: Clean the project
    cmds:
      - rm -rf temp
      - cargo clean
