/// This file is generated by kopgen. Do not edit manually. If you need to make adjustments add it to .openapi-generator-ignore file.
pub async fn setup() -> kube::Client {
    kube::Client::try_default()
        .await
        .expect("Failed to create client")
}
