/*
 * Pets API
 *
 * An API for managing pets
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CatResponse {
    #[serde(rename = "uuid")]
    pub uuid: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "breed")]
    pub breed: String,
    #[serde(rename = "age")]
    pub age: i32,
}

impl CatResponse {
    pub fn new(uuid: String, name: String, breed: String, age: i32) -> CatResponse {
        CatResponse {
            uuid,
            name,
            breed,
            age,
        }
    }
}

