// This file is generated by k8s-codegen crate. Do not edit manually. If you need to make adjustments add it to .openapi-generator-ignore file or edit its template.

use kube::CustomResourceExt;

fn main() {
    let crds = vec![
        k8s_operator::types::cat::Cat::crd(),
        k8s_operator::types::dog::Dog::crd(),
        k8s_operator::types::horse::Horse::crd(),
    ];

    let generated_hint = "# This file is generated by k8s-crdgen crate. Do not edit manually. If you need to make adjustments add it to .openapi-generator-ignore file or edit its template.";
    for crd in crds {
        match serde_yaml::to_string(&crd) {
            Ok(yaml) => print!("{}\n\n---\n{}", generated_hint, yaml),
            Err(e) => eprintln!("Error serializing CRD to YAML: {}", e),
        }
    }
}
