[package]
name = "k8s_crdgen"
version = "0.1.0"
edition = "2021"
description = "Generate Kubernetes CRD from Rust structs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
k8s_operator = { path = "../k8s-operator" }
serde_yaml = "0.9.21"
k8s-openapi = { version = "0.22.0", features = ["v1_26"] }
kube = { version = "0.91.0", default-features = false, features = [
    "rustls-tls",
    "config",
    "client",
    "runtime",
    "derive",
] }
