name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x

      - name: Analyse the code
        run: task analyse

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x

      - name: Check if workspace is dirty
        run: task dirty-check
