name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  dirty-check:
    name: Dirty check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Check for dirty files - files that were generated but not committed
        run: task dirty-check

  validate:
    name: Validate OpenAPI specification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Validate the code
        run: task oas-validate

  analyse:
    name: Analyse code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Analyse the code
        run: task analyse

  build:
    name: Build code
    needs:
      - dirty-check
      - validate
      - analyse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Build
        run: task build

  build-docs:
    name: Build and deploy docs
    needs:
      - dirty-check
      - validate
      - analyse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install mdBook
        run: cargo install mdbook

      - name: Build the book
        run: mdbook build docs/operator

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/operator/book

  test:
    name: End to end test
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Install ctlptl
        run: |
          CTLPTL_VERSION="0.8.29"
          curl -fsSL https://github.com/tilt-dev/ctlptl/releases/download/v$CTLPTL_VERSION/ctlptl.$CTLPTL_VERSION.linux.x86_64.tar.gz | sudo tar -xzv -C /usr/local/bin ctlptl

      - name: Install k3d
        run: |
          K3D_VERSION="5.6.3"
          curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | TAG=v$K3D_VERSION bash

      - name: Use local environment variables
        run: cp .env.example .env

      - name: Test
        run: task test
