---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-cluster-role
rules:
  - apiGroups:
      - example.com
    resources:
      - cats
      - dogs
      - horses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
