---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operator-role # Give this a meaningful name
rules:
  - apiGroups:
      - example.com
    resources:
      - cats
      - dogs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
      - patch
