---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator-role-binding
subjects:
  - kind: ServiceAccount
    name: operator-service-account
roleRef:
  kind: Role
  name: operator-role
  apiGroup: rbac.authorization.k8s.io
